#!/bin/bash

set -e

restore_configs

export V1_VERSION=${V1_VERSION}DL

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/dual-drivers-on-yz
$CFGDIR/boards/skr_pro_dual
$CFGDIR/accessories/laser

opt_add SPINDLE_LASER_PWM_PIN PC9
opt_add SPINDLE_LASER_ENA_PIN PB0 // Heater2


opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set Y2_DRIVER_TYPE  "TMC2209"
opt_set Z2_DRIVER_TYPE  "TMC2209"

opt_set Y2_CURRENT 900
opt_set Z2_CURRENT 900

opt_disable \
    E0_DRIVER_TYPE

# Custom settings

# Name
opt_set CUSTOM_MACHINE_NAME "\"LowRider3 WiFi\""
# Control by RPM
opt_set CUTTER_POWER_UNIT RPM
# RPM min and max for my spindle
opt_set SPEED_POWER_MIN 5000
opt_set SPEED_POWER_MAX 20000
# Enable WiFi serial
opt_set SERIAL_PORT_2 6
opt_set SERIAL_PORT_3 -1

# Important settings from official pre-configured firmware

opt_set Z_MIN_ENDSTOP_INVERTING true
opt_set Z_MIN_PROBE_ENDSTOP_INVERTING true
opt_set DEFAULT_STEPPER_DEACTIVE_TIME 1200
opt_set DISABLE_INACTIVE_Z false

echo "- Configured for custom setup" >> README.md

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
